#############################################################################################
####################               2. Data Cleaning GBIF data            ####################
#############################################################################################


library(tidyverse)
library(sf) 
library(raster) 
library(rgdal) 
library(spData)
library(rnaturalearth)
library(geobr)
library(ggplot2)
library(ggspatial)
library(tmap)
library(tmaptools)
library(grid)
library(mapview)
library(leaflet)
library(knitr)
library(sidrar)
library(landscapetools)
library(dplyr)
library(Taxonstand)
library(CoordinateCleaner)

# Importing and preparing data --------------------------------------------
PperuvianaSpecies <- read_delim("GBIFPperuviana_ago23.csv", 
                                delim = "\t", escape_double = FALSE, col_types = cols(decimalLatitude = col_number(), 
                                                                                     decimalLongitude = col_number()), 
                                trim_ws = TRUE)

Pperuviana <- PperuvianaSpecies %>%
  dplyr::select(gbifID, decimalLatitude, decimalLongitude) 

#conversão para classe sf
PperuvianaSpecies_vetor <- Pperuviana %>% 
  dplyr::relocate(decimalLongitude, decimalLatitude, .after = 1) %>% 
  dplyr::mutate(lon = decimalLongitude, lat = decimalLatitude) %>%
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)

data(world)
#plot(world[1], col = "gray", main = "Mapa do mundo")


# Plotting ocurrences (world) ---------------------------------------------
tmap::tmap_mode(mode = "plot")

tm_shape(world, 
         bbox = PperuvianaSpecies_vetor) +
  tm_polygons() +
  tm_shape(PperuvianaSpecies_vetor) +
  tm_dots(size = .1, col = "forestgreen")

# Checking species taxonomy -----------------------------------------------

sort(unique(PperuvianaSpecies$scientificName))


#Unique species list
species.names <- unique(PperuvianaSpecies$scientificName) 
tax.check <- TPL(species.names)
tax.check

# creating new object w/ original and new names after TPL
new.tax <- data.frame(scientificName = species.names, 
                      genus.new.TPL = tax.check$New.Genus, 
                      species.new.TPL = tax.check$New.Species,
                      status.TPL = tax.check$Taxonomic.status,
                      scientificName.new.TPL = paste(tax.check$New.Genus,
                                                     tax.check$New.Species)) 

#Merging raw data and checked data
occs.new.tax <- merge(PperuvianaSpecies, new.tax, by = "scientificName")

#write.csv(occs.new.tax, 
         # "PperuvianaSpecies_taxonomy_check.csv", 
        #  row.names = FALSE)

# Checking species' coordinates -------------------------------------------


occs.coord <- PperuvianaSpecies[!is.na(PperuvianaSpecies$decimalLatitude) 
                   & !is.na(PperuvianaSpecies$decimalLongitude),]
# output w/ only potential correct coordinates
geo.clean <- clean_coordinates(x = occs.coord, 
                               lon = "decimalLongitude",
                               lat = "decimalLatitude",
                               species = "species", 
                               value = "clean")

#plot the output of clean data

plot(decimalLatitude ~ decimalLongitude, data = geo.clean)
#map(, , , add = TRUE)
par(mfrow = c(1, 1))

geo.clean_vetor <- geo.clean %>% 
  dplyr::relocate(decimalLongitude, decimalLatitude, .after = 1) %>% 
  dplyr::mutate(lon = decimalLongitude, lat = decimalLatitude) %>%
  sf::st_as_sf(coords = c("lon", "lat"), crs = 4326)

tm_shape(world, 
         bbox = geo.clean_vetor) +
  tm_polygons() +
  tm_shape(geo.clean_vetor) +
  tm_dots(size = .1, col = "forestgreen")

#setting value = clean it returns only the potentially correct coordinates. For checking and reproducibility we want to save all the output with the flags generated by the routine
occs.new.geo <- clean_coordinates(x = occs.coord, 
                                  lon = "decimalLongitude",
                                  lat = "decimalLatitude",
                                  species = "species", 
                                  value = "spatialvalid")


occs.new.geo2 <- merge(PperuvianaSpecies, occs.new.geo, 
                       all.x = TRUE, 
                       by = "gbifID")


# Remove impossible, incomplete and unlikely coordinates# -----------------

#colnames(occs.new.geo2)
occ.new.geo4 <- occs.new.geo2 %>%
  dplyr::filter(between(year.x, 1902, 2023) & countryCode.x %in% c("AR", "BR", "PY"))

write.csv(occ.new.geo4, "Pperuviana_coord_checkTOTAL.csv", 
          row.names = FALSE)

